version: '2'

services:
  db:
    build: ./db
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306

volumes:
  db_data: